### ISSUE TITLE
adjust the loudness in the mainExp

### ISSUE THREAD

**Issue by CerenB** [CerenB/RhythmCateg-1#9]
quote: the sound test was waaaay to loud compared to the training sounds, I almost have become deaf!

**Comment by CerenB** [comment]
Where is volume set for the main exp? Not sure if I should change the audio amplitude directly or lower in PsychPortAudio?

**Comment by TomasLenc** [comment]
solved in TomasLenc/RhythmCateg#30

**Comment by CerenB** [comment]
Can you actually undo your changes on this from your logging PR? Because I made some changes all around the scripts. Is yours also all around? :/

**Comment by TomasLenc** [comment]
No, I put one multiplication into makeStimMainExp.m (line 70),
`s = cfg.toneAmplitude * sin(2*pi*currF0*t); `
and the parameter `cfg.toneAmplitude ` is set in getMainExpParameters.m on line 178.

**Comment by CerenB** [comment]
Ok if it's in one place it would be easier to review! thank you!

**Comment by TomasLenc** [comment]
Yeah, it's just those two lines and it would affect all the stimuli in that experiment. But feel free to change/delete etc if you came up with sth else.

**Comment by CerenB** [comment]
Nothing fancy but I changed the function inputs :/ happy to take them down if we go with your option. I've made the PR; combined with frequency dB and loudness
